### ISSUE TITLE
gnome::gsettings does not have "user" parameter

### ISSUE THREAD

**Issue by lesinigo** [camptocamp/puppet-gnome#10]
The example in README.md shows a "user" parameter for the gnome::gsettings resource, but the manifest does not actually have that parameter. The example should be updated but I don't actually know how to use that resource to manage a specific user setting (if at all possible?).

**Comment by syntacticvexation** [comment]
I had the same issue.  Looking through the commit history, adding configs to each user has been deprecated in favour of using system-wide overrides.

Some relevant doco is here:
https://developer.gnome.org/gio/stable/glib-compile-schemas.html

**Comment by Phil-Friderici** [comment]
Think this issue could get closed now that the README fix got merged.

**Comment by raphink** [comment]
Fixed in da7987c03c35d27f4f1dc76170159071c62cb31b
