### ISSUE TITLE
Support overriding for a single user

### ISSUE THREAD

**Issue by looppair** [camptocamp/puppet-gnome#17]
It would be good if there was a `$user` parameter to override settings for a single user.

**Comment by brwyatt** [comment]
I put some work into this on my dev branch of this: https://github.com/brwyatt/puppet-gnome/tree/dev

It isn't a perfect solution in general, but it works. Needs some cleanup, but it does function. (It will also work if a session is currently running, as I found the previous method wouldn't work and would get overridden by the current session)

**Comment by raphink** [comment]
Fixed in #23
